[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "@solady/contracts/=lib/solady/src"
]

[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimismSepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
gnosis = "https://rpc.gnosischain.com"
chiado = "https://rpc.chiadochain.net"
base = "https://mainnet.base.org"
baseGoerli = "https://goerli.base.org"
baseSepolia = "https://sepolia.base.org"
polygonZkEvm = "https://polygonzkevm-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonZkEvmTestnet = "https://polygonzkevm-testnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
zkSyncTestnet = "https://testnet.era.zksync.dev"
zkSync = "https://mainnet.era.zksync.io"
scrollSepolia = "https://sepolia-rpc.scroll.io"
scroll = "https://rpc.scroll.io"
alephZeroTestnet = "https://rpc.alephzero-testnet.gelato.digital"
celo-testnet = "https://alfajores-forno.celo-testnet.org"
zircuitTestnet = "https://zircuit1-testnet.p2pify.com/"
mantle-testnet = "https://rpc.sepolia.mantle.xyz"
sei = "https://evm-rpc.sei-apis.com	"
# morphHolesky = "${MORPH_HOLESKY_RPC}"
# lineaSepolia = "${LINEA_SEPOLIA_RPC}"
# zircuit = "${ZIRCUIT_TESTNET_RPC}"
# apechain = "${APECHAIN_JENKINS_RPC}"
# zeroSepolia = "${ZERO_SEPOLIA_RPC}"

[etherscan]
# polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# celoTestnet = { key = "${CELO_API_KEY}", chain = 44787, url="https://alfajores.celoscan.io" }
# scrollSepolia = { key = "${SCROLL_API_KEY}", chain = 534351, url = "https://api-sepolia.scrollscan.com/api" }
# optimismSepolia = { key = "${OPTIMISM_API_KEY}", chain = 11155420, url = "https://api-sepolia-optimistic.etherscan.io/api" }
# baseSepolia = { key = "${BASE_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }
# arbitrumSepolia = { key = "${ARBITRUM_API_KEY}", chain = 421614, url = "https://api-sepolia.arbiscan.io/api" }
# lineaSepolia = { key = "${LINEA_API_KEY}", chain = 59141, url = "https://api-sepolia.lineascan.build/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options